
   ERROR  Command "make:filament-" is ambiguous. Did you mean one of these?  

  ⇂ make:filament-exporter  
  ⇂ make:filament-importer  
  ⇂ make:filament-cluster  
  ⇂ make:filament-page  
  ⇂ make:filament-panel  
  ⇂ make:filament-relation-manager  
  ⇂ make:filament-resource  
  ⇂ make:filament-theme  
  ⇂ make:filament-user  
  ⇂ make:filament-rich-content-custom-block  
  ⇂ make:filament-form-field  
  ⇂ make:filament-form  
  ⇂ make:filament-livewire-form  
  ⇂ make:filament-infolist-entry  
  ⇂ make:filament-schema-component  
  ⇂ make:filament-livewire-schema  
  ⇂ make:filament-schema  
  ⇂ make:filament-issue  
  ⇂ make:filament-table-column  
  ⇂ make:filament-livewire-table  
  ⇂ make:filament-table  
  ⇂ make:filament-widget  

